version: '3.7'

services:
  proxy:
    image: bvi_proxy:latest
    build:
      context: ./proxy
    ports:
      - 8996:8080
    volumes:
      - ./:/usr/src/project
      - ./static_django/:/usr/src/project/static_django/
    depends_on:
      - back
      - front
    networks:
      - bvi_network
  front:
    image: bvi_front:latest
    build:
      context: ./front
    networks:
      - bvi_network
  back:
    build:
      context: ./back
    image: bvi_back:latest
    volumes:
      - ./media/:/usr/src/project/media/
      - ./static_django/:/usr/src/project/static_django/
    depends_on:
      - db
    networks:
      - bvi_network
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_traefik
      POSTGRES_USER: django_traefik
      POSTGRES_PASSWORD: django_traefik
    networks:
      - bvi_network

volumes:
  postgres_data:

networks:
  bvi_network:
    driver: overlay