# Generated by Django 6.0.4 on 2026-08-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commentary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
    ]
