# Generated by Django 6.0.4 on 2026-07-13 13:36

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Групповые чаты',
                'verbose_name_plural': 'Групповые чаты',
            },
        ),
        migrations.CreateModel(
            name='TypeClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип группы',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementGlobal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='media/')),
                ('announce', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('for_all', models.BooleanField(default=False, verbose_name='Общее')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявления общие',
                'verbose_name_plural': 'Объявления общие',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementInClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='media/')),
                ('announce', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.classmodel')),
            ],
            options={
                'verbose_name': 'Объявления для класса',
                'verbose_name_plural': 'Объявления для класса',
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_child_chat', models.DateTimeField(blank=True, null=True)),
                ('last_read_parent_chat', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='messenger.classmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Таблица связей учитель-класс',
                'verbose_name_plural': 'Таблица связей учитель-класс',
            },
        ),
        migrations.CreateModel(
            name='DeletedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('info_about', models.CharField(blank=True, max_length=300, null=True, verbose_name='Информация о сообщении')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Удалённые сообщения',
                'verbose_name_plural': 'Удалённые сообщения',
            },
        ),
        migrations.CreateModel(
            name='GroupLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='messenger.groupmodel')),
            ],
        ),
        migrations.AddField(
            model_name='classmodel',
            name='child_chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_group', to='messenger.groupmodel'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='parent_chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_group', to='messenger.groupmodel'),
        ),
        migrations.CreateModel(
            name='MessageInGroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.groupmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщения в группах',
                'verbose_name_plural': 'Сообщения в группах',
            },
        ),
        migrations.CreateModel(
            name='MessageInTeacherChatModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='Сообщение')),
                ('from_teacher', models.BooleanField(default=False, verbose_name='От педагога')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_messages', to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщения с педагогом',
                'verbose_name_plural': 'Сообщения с педагогом',
            },
        ),
        migrations.CreateModel(
            name='ClassTypesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_links', to='messenger.classmodel')),
                ('type_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_links', to='messenger.typeclassmodel')),
            ],
            options={
                'verbose_name': 'Таблица связей тип-класс',
                'verbose_name_plural': 'Таблица связей тип-класс',
            },
        ),
        migrations.CreateModel(
            name='AnnounceTypeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.announcementglobal')),
                ('type_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.typeclassmodel')),
            ],
            options={
                'verbose_name': 'Таблица связей тип-объявление',
                'verbose_name_plural': 'Таблица связей тип-объявление',
            },
        ),
    ]
