# Generated by Django 6.0.4 on 2026-07-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeclassmodel',
            options={'verbose_name': 'Тип группы', 'verbose_name_plural': 'Типы групп'},
        ),
    ]
