# Generated by Django 6.0.4 on 2026-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_typeclassmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageingroupmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
