# Generated by Django 6.0.4 on 2026-08-12 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_messageingroupmodel_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinteacherchatmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeacherTeacherMetaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=20)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherLinkCompanion', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherLinkTeacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Системная информация по чатам препод-препод',
                'verbose_name_plural': 'Системная информация по чатам препод-препод',
            },
        ),
    ]
