# Generated by Django 6.0.4 on 2026-08-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_messageinteacherchatmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcetypelink',
            name='announce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_links', to='messenger.announcementglobal'),
        ),
        migrations.AlterField(
            model_name='announcetypelink',
            name='type_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_links', to='messenger.typeclassmodel'),
        ),
    ]
