# Generated by Django 6.0.4 on 2026-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_announcetypelink_announce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementglobal',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
