# Docker DNS
resolver 127.0.0.11 ipv6=off valid=15s;
resolver_timeout 5s;
client_max_body_size 300M;

server {
    listen 8080;
    server_name localhost;

    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    proxy_read_timeout 300;
    send_timeout 300;

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        set $upstream_backend 'back:8080';
        proxy_pass http://$upstream_backend;
    }

    location /api/ {
        proxy_set_header Host $http_host;
        set $upstream_backend 'back:8080';
        proxy_pass http://$upstream_backend;
    }

    location /static_django/ {
        alias /usr/src/project/static_django/;
    }

    location /media/ {
        alias /usr/src/project/media/;
    }

    location / {
        set $upstream_frontend 'front:80';
        proxy_pass http://$upstream_frontend;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
    }
}
