# Generated by Django 6.0.4 on 2026-07-13 13:36

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularLessonModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20, verbose_name='День недели')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предмет')),
                ('start_time', models.TimeField(default=datetime.datetime(2026, 7, 13, 13, 36, 5, 776002), verbose_name='Начало')),
                ('finish_time', models.TimeField(default=datetime.datetime(2026, 7, 13, 13, 36, 5, 776020), verbose_name='Конец')),
                ('start_schedule', models.DateField(default=datetime.date.today, verbose_name='Дата начала действия расписания')),
                ('end_schedule', models.DateField(default=datetime.date.today, verbose_name='Дата окончания действия расписания')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.classmodel', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Регулярные занятия',
                'verbose_name_plural': 'Регулярные занятия',
            },
        ),
        migrations.CreateModel(
            name='CancelLessonModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата отмены')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceled', to='schedule.regularlessonmodel', verbose_name='Отменённое занятие')),
            ],
            options={
                'verbose_name': 'Отмены занятий',
                'verbose_name_plural': 'Отмены занятий',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Педагог (в расписании)',
                'verbose_name_plural': 'Педагог (в расписании)',
            },
        ),
        migrations.AddField(
            model_name='regularlessonmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.teachermodel', verbose_name='Педагог'),
        ),
        migrations.CreateModel(
            name='IrregularLessonModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предмет')),
                ('start_time', models.TimeField(default=datetime.datetime(2026, 7, 13, 13, 36, 5, 776672), verbose_name='Начало')),
                ('finish_time', models.TimeField(default=datetime.datetime(2026, 7, 13, 13, 36, 5, 776687), verbose_name='Конец')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.classmodel', verbose_name='Группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.teachermodel', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Разовые занятия',
                'verbose_name_plural': 'Разовые занятия',
            },
        ),
    ]
