# Generated by Django 6.0.4 on 2026-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellessonmodel',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='irregularlessonmodel',
            name='finish_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='irregularlessonmodel',
            name='start_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='end_schedule',
            field=models.DateField(auto_now_add=True, verbose_name='Дата окончания действия расписания'),
        ),
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='finish_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='start_schedule',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала действия расписания'),
        ),
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='start_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Начало'),
        ),
    ]
