# Generated by Django 6.0.4 on 2026-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_cancellessonmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irregularlessonmodel',
            name='finish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='irregularlessonmodel',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
