# Generated by Django 6.0.4 on 2026-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_irregularlessonmodel_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='end_schedule',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия расписания'),
        ),
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='finish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='start_schedule',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия расписания'),
        ),
        migrations.AlterField(
            model_name='regularlessonmodel',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
